# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_time', models.DateField(verbose_name='\u5386\u53f2\u65f6\u95f4')),
                ('publish_time', models.DateField(verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('problem', models.TextField(verbose_name='\u6574\u6539\u95ee\u9898')),
                ('problem_origin', models.CharField(max_length=50, verbose_name='\u95ee\u9898\u6765\u6e90')),
                ('problem_platform', models.CharField(max_length=50, verbose_name='\u53d1\u5e03\u5e73\u53f0')),
                ('problem_attribute', models.CharField(max_length=50, verbose_name='\u95ee\u9898\u5c5e\u6027')),
                ('problem_reason', models.TextField(blank=True, verbose_name='\u95ee\u9898\u539f\u56e0')),
                ('consequence', models.TextField(blank=True, verbose_name='\u95ee\u9898\u540e\u679c')),
                ('problem_level', models.CharField(max_length=50, verbose_name='\u95ee\u9898\u7b49\u7ea7')),
                ('responsiblity', models.CharField(max_length=50, verbose_name='\u8d23\u4efb\u5355\u4f4d')),
                ('publisher', models.CharField(max_length=50, verbose_name='\u53d1\u5e03\u4eba\u5458')),
                ('deadline', models.DateField(verbose_name='\u6574\u6539\u671f\u9650')),
            ],
            options={
                'verbose_name': '\u5b89\u5168\u4fe1\u606f\u6570\u636e\u5e93',
                'verbose_name_plural': '\u5b89\u5168\u4fe1\u606f\u6570\u636e\u5e93',
            },
        ),
    ]
